image: registry.cn-hangzhou.aliyuncs.com/verystar/golang:prod-v0.0.1

include:
  - remote: 'https://raw.githubusercontent.com/verystar/devops/master/jobs/go-build.yml'
  - remote: 'https://raw.githubusercontent.com/verystar/devops/master/jobs/go-test.yml'
  - remote: 'https://raw.githubusercontent.com/verystar/devops/master/jobs/code-scan.yml'

stages:
  - build
  - test
  - code_scan

build:
  stage: build
  tags:
    - k8s
  extends: .build

test:
  stage: test
  tags:
    - k8s
  extends: .test
  allow_failure: true

code_scan:
  stage: code_scan
  tags:
    - k8s
  extends: .code_scan