include:
  - remote: 'https://raw.githubusercontent.com/verystar/devops/master/jobs/python-install.yml'
  - remote: 'https://raw.githubusercontent.com/verystar/devops/master/jobs/code-scan.yml'

variables:
  BUILD_CACHE_DIR: "/home/gitlab-runner/cache"

stages:
  - install
  - code_scan

install:
  stage: install
  tags:
    - k8s
  extends: .install

code_analysis:
  stage: code_scan
  tags:
    - k8s
  extends: .code_scan
